### ISSUE TITLE
Django-storages version is not compatible with django 4.0

### ISSUE THREAD

**Issue by fabienheureux** [wagtail/bakerydemo#321]
The current version of django-storages requires version < 1.9, which is not compatible with django 4.0.

Here is the error I get with django 4.0 
```
django.core.exceptions.ImproperlyConfigured: Could not load Boto3's S3 bindings. cannot import name 'Mapping' from 'collections' (/app/.heroku/python/lib/python3.10/collections/__init__.py)
```

Is there a compatibility issue with versions >= 1.9 ? 

I had a similar issue with boto3 version after upgrading django to 4.0
```python
django.core.exceptions.ImproperlyConfigured: Could not load Boto3's S3 bindings. cannot import name 'Mapping' from 'collections' (/app/.heroku/python/lib/python3.10/collections/__init__.py)
``` 

I used this branch that pinned boto3 and storages to the latest available versions without issues with django 4.0 : https://github.com/wagtail/bakerydemo/compare/master...l-etabli:fix/bump-storages-version-to-support-django4.0?expand=1

**Comment by thibaudcolas** [comment]
I believe this has been fixed in #393.
